### PR TITLE
Add FBGEMM based embeddingbag ubench

### PR DESCRIPTION
**Pull request by nrsatish**

### CODE REVIEW

**Comment by erichan1** [comment]
@nrsatish Can you change the logger to bmlogger? We are migrating to bmlogger (which is mainly just a name change so no fb5, but also a little different in usage). bmlogger defines a get_bmlogger method that returns a logger. If no logging file path is given, the returned logger does nothing when called, which removes the need to add if statements everywhere to check for logger existence. See an example of how to use it here #72 - shouldn't be too hard to switch.

**Comment by nrsatish** [comment]
> @nrsatish Can you change the logger to bmlogger? We are migrating to bmlogger (which is mainly just a name change so no fb5, but also a little different in usage). bmlogger defines a get_bmlogger method that returns a logger. If no logging file path is given, the returned logger does nothing when called, which removes the need to add if statements everywhere to check for logger existence. See an example of how to use it here #72 - shouldn't be too hard to switch.

Done

**Review by erichan1 — APPROVED** [review]
LGTM! Thanks for helping migrate to bmlogger.

**Review by aaronenyeshi — APPROVED** [review]
The bash script looks good to me! (May want to add -f to usage as well). Will let others take a deeper look into the ubench itself.

**Review by samiwilf — APPROVED** [review]
LGTM!

**Pull request merged**
