### PR TITLE
convert famlogger to bmlogger with nop

### PR DESCRIPTION
**Pull request by erichan1**
Add benchmark logger (bmlogger) to make transition to new logger. 

Changes
1. Thanks to @samiwilf, add no op logger instead of conditionals.
2. Change name of fb5logger to bmlogger 
3. Squashed in a stacked PR #56 for adding XLMR warmup. I really should have merged this PR and #56 in when they were both approved separately. Please skip over xlmr.py changes in this PR since those were already approved.

### CODE REVIEW

**Comment by aaronenyeshi** [comment]
Could you please rebase this, I think some of these changes are already in main

**Review by aaronenyeshi — CHANGES_REQUESTED** [review]
Please make the same name changes to DLRM and RNN-T, I only see XLMR here.

**Comment by erichan1** [comment]
> Please make the same name changes to DLRM and RNN-T, I only see XLMR here.

@aaronenyeshi This is on purpose. The repo will have two loggers temporarily. fb5logger (the old one) and bmlogger (the new one). I'd like to make this conversion first as an intermediate step.

**Review by aaronenyeshi — APPROVED** [review]
Okay that makes sense, lets follow up in separate PRs for DRLM/RNN-T

**Pull request merged**
